name: Build and Upload APK to Release

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  release:
    types: [published]  # ← dispara quando uma release é publicada

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the app
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload debug APK as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: ignore

      - name: Upload release APK to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
