name: Publish to self-hosted F-Droid repo

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fdroid:
    name: Build and publish F-Droid repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Determine app version
        id: version
        run: |
          python - <<'PY'
          import os
          import pathlib
          import re

          text = pathlib.Path('app/build.gradle').read_text()
          name = re.search(r'versionName\s+"([^"]+)"', text).group(1)
          code = re.search(r'versionCode\s+(\d+)', text).group(1)

          with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as fh:
              fh.write(f"version_name={name}\n")
              fh.write(f"version_code={code}\n")
          PY

      - name: Prepare F-Droid workspace
        run: |
          mkdir -p fdroid/repo fdroid/icons
          cp app/src/main/res/mipmap-xxxhdpi/ic_launcher.png fdroid/icons/com.erikraft.drop.png
          cp "app/build/outputs/apk/release/erikraftdrop_v${{ steps.version.outputs.version_name }}.apk" \
             "fdroid/repo/com.erikraft.drop_${{ steps.version.outputs.version_code }}.apk"

      - name: Update F-Droid metadata
        run: scripts/update_fdroid_metadata.py

      - name: Install fdroidserver
        run: |
          python -m pip install --upgrade pip
          pip install fdroidserver

      - name: Write F-Droid config
        env:
          FDROID_REPO_URL: ${{ secrets.FDROID_REPO_URL }}
          FDROID_REPO_NAME: ${{ secrets.FDROID_REPO_NAME }}
          FDROID_REPO_DESCRIPTION: ${{ secrets.FDROID_REPO_DESCRIPTION }}
          FDROID_REPO_ADDRESS: ${{ secrets.FDROID_REPO_ADDRESS }}
          FDROID_KEY_ALIAS: ${{ secrets.FDROID_KEY_ALIAS }}
          FDROID_KEY_PASSWORD: ${{ secrets.FDROID_KEY_PASSWORD }}
          FDROID_KEYSTORE_PASSWORD: ${{ secrets.FDROID_KEYSTORE_PASSWORD }}
        run: scripts/write_fdroid_config.sh

      - name: Decode F-Droid keystore
        env:
          FDROID_KEYSTORE_BASE64: ${{ secrets.FDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$FDROID_KEYSTORE_BASE64" | base64 --decode > fdroid/keystore.jks

      - name: Build repository index
        run: |
          cd fdroid
          fdroid update --create-metadata --pretty

      - name: Publish F-Droid repo branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: fdroid/repo
          publish_branch: fdroid
          force_orphan: true

      - name: Clean sensitive files
        if: always()
        run: |
          rm -f fdroid/keystore.jks fdroid/config.yml
