from pathlib import Path

root = Path(__file__).resolve().parents[2]

# WebKit 1.17 contains the current proxy override APIs.
build = root / 'app/build.gradle'
s = build.read_text(encoding='utf-8').replace("androidx.webkit:webkit:1.14.0", "androidx.webkit:webkit:1.17.0")
build.write_text(s, encoding='utf-8')

# Remove accidental duplicate onion condition/server generated by the first transformation pass.
f = root / 'app/src/main/java/com/erikraft/drop/OnboardingFragment2.java'
s = f.read_text(encoding='utf-8')
dup_condition = '''            } else if (url.toLowerCase().contains(".onion")) {\n                String onionUrl = url.contains("://") ? url : "http://" + url;\n                if (!onionUrl.endsWith("/")) onionUrl += "/";\n                newServer(onionUrl);\n            } else if (url.toLowerCase().contains(".onion")) {\n                String onionUrl = url.contains("://") ? url : "http://" + url;\n                if (!onionUrl.endsWith("/")) onionUrl += "/";\n                newServer(onionUrl);'''
s = s.replace(dup_condition, '''            } else if (url.toLowerCase().contains(".onion")) {\n                String onionUrl = url.contains("://") ? url : "http://" + url;\n                if (!onionUrl.endsWith("/")) onionUrl += "/";\n                newServer(onionUrl);''')
dup_server = '''        servers.add(new ServerItem("http://nozudb2e4jy4betognmnwoxvdu44wvjoqvmwios5ql7mxagqqpnn64ad.onion/", "ErikrafT Drop™ Onion Service (Beta)", "Requer Tor. O PairDrop fica como quinto servidor."));\n        servers.add(new ServerItem("http://nozudb2e4jy4betognmnwoxvdu44wvjoqvmwios5ql7mxagqqpnn64ad.onion/", "ErikrafT Drop™ Onion Service (Beta)", "Requer Tor. O PairDrop fica como quinto servidor."));'''
s = s.replace(dup_server, dup_server.split('\n')[0])
dup_exclusion = '''                    && !url.equals("http://nozudb2e4jy4betognmnwoxvdu44wvjoqvmwios5ql7mxagqqpnn64ad.onion/")\n                    && !url.equals("http://nozudb2e4jy4betognmnwoxvdu44wvjoqvmwios5ql7mxagqqpnn64ad.onion/")'''
s = s.replace(dup_exclusion, '                    && !url.equals("http://nozudb2e4jy4betognmnwoxvdu44wvjoqvmwios5ql7mxagqqpnn64ad.onion/")')
f.write_text(s, encoding='utf-8')

# Use the AndroidX-compatible main executor for minSdk 21.
t = root / 'app/src/main/java/com/erikraft/drop/TorController.java'
s = t.read_text(encoding='utf-8')
s = s.replace('import androidx.annotation.NonNull;\n', 'import androidx.annotation.NonNull;\nimport androidx.core.content.ContextCompat;\n')
s = s.replace('mainExecutor = app.getMainExecutor();', 'mainExecutor = ContextCompat.getMainExecutor(app);')
t.write_text(s, encoding='utf-8')
